#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2026 Henrique Almeida <me@h3nc4.com>

# Names the image a CI job should run in, and exports the docker invocation its steps use.
# A change touching the image inputs is built from the checkout, so the job exercises the
# candidate rather than the published image it is about to replace. Nothing is pushed: the
# image stays in this runner's daemon, which is why callers reach it through docker run
# rather than a container job, and why every job resolves this for itself.
#
# Called by the action beside it, which documents every variable read here. Writes image to
# GITHUB_OUTPUT, and DEV_IMAGE and DEV_RUN to GITHUB_ENV.

set -eu

: "${PUBLISHED_REPO:?PUBLISHED_REPO is not set}"
: "${GITHUB_OUTPUT:?GITHUB_OUTPUT is not set. This runs under GitHub Actions.}"
: "${GITHUB_ENV:?GITHUB_ENV is not set. This runs under GitHub Actions.}"

cd "${GITHUB_WORKSPACE:?GITHUB_WORKSPACE is not set. This runs under GitHub Actions.}"

workdir="${WORKDIR:-/workspace}"
dockerfile="${DOCKERFILE:-docker/dev.Dockerfile}"
version_file="${VERSION_FILE:-.github/VERSION}"
image_inputs="${IMAGE_INPUTS:-docker/dev.Dockerfile scripts/entrypoint.sh scripts/switch-user.sh}"

# A first push to a branch reports an all-zero base and has nothing to compare against, so
# treat the image as untouched. A base that no longer resolves, after a force-push, is the
# opposite case: nothing can be ruled out, so build.
changed=""
case "${BASE_SHA:-}" in
  "" | 0000000000000000000000000000000000000000) ;;
  *)
    if git cat-file -e "${BASE_SHA}^{commit}" 2>/dev/null; then
      # image_inputs is a space-separated list of paths, so it is split on purpose.
      # shellcheck disable=SC2086
      set -- ${image_inputs}
      changed="$(git diff --name-only "${BASE_SHA}" HEAD -- "$@")"
    else
      changed="(base ${BASE_SHA} unreachable)"
    fi
    ;;
esac

image=""
if [ -z "${changed}" ]; then
  published="${PUBLISHED_REPO}:$(cat "${version_file}")"
  if docker pull -q "${published}" >/dev/null 2>&1; then
    image="${published}"
    echo "Image inputs untouched; using ${image}" >&2
  else
    changed="${published} could not be pulled"
    echo "::warning::${changed}, so it is being built from this checkout instead." \
      "Otherwise check the tag in ${version_file}, and whether this job logs in to the registry."
  fi
fi

if [ -z "${image}" ]; then
  # No namespace, so nothing tries to pull this from a registry.
  image="${PUBLISHED_REPO##*/}:candidate"
  echo "Building ${image} from this checkout:" >&2
  echo "${changed}" | sed 's/^/  /' >&2
  set -- build
  if [ -n "${CACHE_FROM:-}" ] || [ -n "${CACHE_TO:-}" ]; then
    set -- buildx build --load
    if [ -n "${CACHE_FROM:-}" ]; then set -- "$@" --cache-from "${CACHE_FROM}"; fi
    if [ -n "${CACHE_TO:-}" ]; then set -- "$@" --cache-to "${CACHE_TO}"; fi
  fi
  docker "$@" -f "${dockerfile}" -t "${image}" .
fi

uid="$(id -u)"
gid="$(id -g)"

entrypoint="/bin/bash"
if ! docker run --rm --entrypoint "${entrypoint}" "${image}" -c ':' >/dev/null 2>&1; then
  entrypoint="/bin/sh"
fi
echo "Running commands through ${entrypoint}" >&2

case "${PWD}" in
  *"'"*)
    echo "The checkout path contains a single quote, which cannot be quoted here." >&2
    exit 1
    ;;
  *) ;;
esac

runner="${RUNNER_TEMP:-/tmp}/dev-run"
{
  echo '#!/bin/sh'
  echo '# Generated by h3nc4/dev-image-action. Runs one command in the dev image.'
  printf 'exec docker run --rm --user %s:%s --entrypoint %s' "${uid}" "${gid}" "${entrypoint}"
  printf " -v '%s':'%s' -e HOME=/tmp -w '%s'" "${PWD}" "${workdir}" "${workdir}"
  if [ -n "${DOCKER_ARGS:-}" ]; then
    printf ' %s' "${DOCKER_ARGS}"
  fi
  printf " '%s' \"\$@\"\n" "${image}"
} >"${runner}"
chmod +x "${runner}"

echo "image=${image}" >>"${GITHUB_OUTPUT}"
{
  echo "DEV_IMAGE=${image}"
  echo "DEV_RUN=${runner}"
} >>"${GITHUB_ENV}"
